import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";
import fs from "fs";
import path from "path";
import os from "os";

async function main() {
  const envDir = path.join(os.homedir(), ".agent_economy_wallet");
  if (!fs.existsSync(envDir)) {
    fs.mkdirSync(envDir, { recursive: true });
  }

  const envFile = path.join(envDir, ".env");

  if (
    fs.existsSync(envFile) &&
    fs.readFileSync(envFile, "utf-8").includes("AGENT_ECONOMY_PUBLIC_KEY")
  ) {
    console.log("Wallet already provisioned.");
    return;
  }

  console.log(`Provisioning local wallet...`);

  // Generate keypair for OpenClaw skill
  const keypair = Keypair.generate();
  const publicKey = keypair.publicKey.toBase58();
  const secretKey = bs58.encode(keypair.secretKey);

  const envContent = `# Auto-generated by OpenClaw Agent Economy Wallet Skill
AGENT_ECONOMY_PUBLIC_KEY=${publicKey}
AGENT_ECONOMY_SECRET_KEY=${secretKey}
SOLANA_CLUSTER=devnet
SOLANA_RPC_URL=https://api.devnet.solana.com
`;

  fs.writeFileSync(envFile, envContent);

  console.log("✅ Wallet provisioned.");
  console.log(`Address: ${publicKey}`);
}

main().catch(console.error);
